dist: bionic
language: cpp
compiler:
- i686-w64-mingw32-g++

before_install:
- sudo apt-get install pkg-config
# Remove libc6-dev so it won't conflict with mingw libs
# - sudo apt-get remove libc6-dev

# Download and extract development libraries under /usr/local

# SDL2
- curl -SL https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz | tar -xzC /tmp && sudo cp -R /tmp/SDL2-2.0.10/i686-w64-mingw32/* /usr/local/

# SDL_ttf
- curl -SL https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-mingw.tar.gz | tar -xzC /tmp && sudo cp -R /tmp/SDL2_ttf-2.0.15/i686-w64-mingw32/* /usr/local/

# zlib
- curl -SL http://zlib.net/zlib-1.2.11.tar.gz | tar -xz

# Freetype
- curl -SL http://downloads.sourceforge.net/project/freetype/freetype2/2.8/freetype-2.8.tar.gz | tar -xz
#- curl -SL https://sourceforge.net/projects/gnuwin32/files/freetype/2.3.5-1/freetype-2.3.5-1-lib.zip/download --output /tmp/freetype-2.3.5-1-lib.zip && sudo unzip /tmp/freetype-2.3.5-1-lib.zip -d /usr/local/

script:
# Compile and install zlib under /usr/i686-w64-mingw32/lib
- cd zlib*
# zlib 'configure' script is currently broken, use win32/Makefile.gcc directly
- sed -e s/"PREFIX ="/"PREFIX = i686-w64-mingw32-"/ -i win32/Makefile.gcc
- make -f win32/Makefile.gcc
- sudo BINARY_PATH=/usr/i686-w64-mingw32/bin INCLUDE_PATH=/usr/i686-w64-mingw32/include LIBRARY_PATH=/usr/i686-w64-mingw32/lib make -f win32/Makefile.gcc install
 
- make

deploy:
  provider: releases
  api_key:
    secure: k4t7yomZFFIzq8yt+cd84dSnzFLrJdWA3hCyHxhIWezl2mZddZurOL6WtTnUIkkaFv6QBQKDGt6DhrrJkPoXoIuvekxYrhKKHkXdk2vBncIWnN+izM58AO1adn18NkqTij7rrCbDzPhJ+9lxSrrrkHpk6lRvNGpHG7kZSRSZkA3qqxUuLX8NlbrvOvMJYhMkbrKEMhx4/964FAypN/sHUtsTm2n4IWnCpAeJREFw3Pbep+6QJR3IH3ExUmMvTMO+DLojKZeElkqy61YxWTFDegrLspMLPz8tjoUgk4t9vFk+NVvMjqNhQVEiaFmPUd3a5mGjK49nwz0Yv56EDUU1Ap5wIZuZbWC6HcJa93dm577AVw4oJbwu2+eHsVa9+8qhbcq+u6Zr7BaBTEVMPw4yKu0dt72Rdr/RKsA1FYb6Xiq3h/M3YwwON8uWwjQwkABk+0Xkt6TgYnBI2nJvf1gkXqBkmcwJClNvKB5T2lxVq7VuA/r4NONn33awbhTNAFLbmbpkp7tf/HfKj9QFopBgFjTnOwOC8fi54QuKZq5SXH85Q9IlbVdgz6g33GHggVuxTKWk+y0cnNCaWWDcQOldfejndgjXtVxr6ftDkVc4uKvZwZZcUAOZsFAqgOZDW8MO+jOGs2ReOY7x1l+RRHGAirdivLjMYBJMchEyf0IcY4Y=
  file: bin/meeting-countdown.exe
  skip_cleanup: true
  on:
    tags: true
    repo: iqqmuT/meeting-countdown
